name: Doxygen generation and deployment to GitHub Pages

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: DenverCoder1/doxygen-github-pages-action@v1
        with: 
          github_token: ${{secrets.GITHUB_TOKEN}}
