name: Doxygen generation and deployment to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: DenverCoder1/doxygen-github-pages-action@v1
        with: 
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: gh-pages-nightly
